services:
  database:
    build: ./back
    image: database
	environment:
		MARIADB_DATABASE: web_db
		MARIADB_ROOT_PASSWORD: pass
    volumes:
      - database:/var/lib/mysql
    ports:
      - 3000:3306
  
  webserver:
    build: ./front
    image: webserver
    ports:
      - "8080:8888"

volumes:
  database: {}
